08-rails/moma/config/routes.rb
Rails.application.routes.draw do
  root :to => 'works#index'
  resources :artists # both plural
  resources :works
end

08-rails/moma/app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :works
end

08-rails/moma/app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :artist, :optional => true
end

08-rails/moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find params[:id]
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist # show page
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist # show page
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path # index page
  end

  # Strong params
  private
  def artist_params
    params.require(:artist).permit(:name, :nationality, :dob, :period, :image)
  end
end

08-rails/moma/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def show
    @work = Work.find params[:id]
  end

  def new
    @work = Work.new
  end

  def create
    work = Work.create work_params
    redirect_to work
  end

  def edit
    @work = Work.find params[:id]
  end

  def update
    work = Work.find params[:id]
    work.update work_params
    redirect_to work # show page
  end

  def destroy
    work = Work.find params[:id]
    work.destroy
    redirect_to works_path
  end

  private
  def work_params
    params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
  end
end

08-rails/moma/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%= f.label :dob, 'Date of birth' %>
  <%= f.text_field :dob, :placeholder => 'YYYY-MM-DD' %>

  <%= f.label :period %>
  <%= f.text_field :period %>

  <%= f.label :image %>
  <%= f.url_field :image %>

  <%= f.submit %>
<% end %>

08-rails/moma/app/views/artists/index.html.erb
<h1>All Artists</h1>

<% @artists.each do |artist| %>
  <%= image_tag artist.image, :class => 'thumb' if artist.image.present? %>
  <ul>
    <li>Name: <%= link_to artist.name, artist %></li>
    <li>Nationality: <%= artist.nationality %></li>
    <% if artist.dob.present? %>
      <li>Date of birth: <%= artist.dob.strftime '%A, %B %e, %Y' %></li>
    <% end %>
    <li>Period: <%= artist.period %></li>
  </ul>
<% end %>

08-rails/moma/app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render :partial => 'form' %>

08-rails/moma/app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<%= image_tag @artist.image, :class => 'feature' if @artist.image.present? %>
<ul>
  <li>Name: <%= @artist.name %></li>
  <li>Nationality: <%= @artist.nationality %></li>
  <li>Date of birth: <%= @artist.dob.strftime '%A, %B %e, %Y' if @artist.dob.present? %></li>
  <li>Period: <%= @artist.period %></li>
</ul>

<% @artist.works.each do |work| %>
  <%= link_to image_tag(work.image, :class => 'thumb'), work %>
<% end %>

<div class="controls">
  <%= link_to 'Edit artist', edit_artist_path(@artist) %>
  <%= link_to 'Delete artist', @artist, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>

08-rails/moma/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <%= link_to 'Works', works_path %>
        <%= link_to 'New Work', new_work_path %>
        |
        <%= link_to 'Artists', artists_path %>
        <%= link_to 'New Artist', new_artist_path %>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>