08-rails/tunr/config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:index, :new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :mixtapes, :only => [:new, :create]
end

08-rails/tunr/app/models/album.rb
class Album < ApplicationRecord
  has_many :songs
end

08-rails/tunr/app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :genres, :through => :songs
end

08-rails/tunr/app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :songs
end

08-rails/tunr/app/models/mixtape.rb
class Mixtape < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :songs
end

08-rails/tunr/app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album, :optional => true
  belongs_to :artist, :optional => true
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :mixtapes
end

08-rails/tunr/app/models/user.rb
class User < ApplicationRecord
  has_many :mixtapes
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
end

08-rails/tunr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present? # Log out non-existant users.
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end
end

08-rails/tunr/app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  before_action :check_for_login

  def new
    @mixtape = Mixtape.new
  end

  def create
    mixtape = Mixtape.create mixtape_params
    @current_user.mixtapes << mixtape
    # @current_user.mixtapes.create mixtape_params
    redirect_to root_path # IRL: go to the show page for the mixtape.
  end

  private
  def mixtape_params
    params.require(:mixtape).permit(:title)
  end
end

08-rails/tunr/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

08-rails/tunr/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path # match
    else
      flash[:error_message] = "Invalid email or password"
      redirect_to login_path # no match, try again
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

08-rails/tunr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  # Fat Models, Thin Controllers

  def create
    @user = User.new user_params

    if @user.save # returns truthy on success
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

08-rails/tunr/app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

08-rails/tunr/app/helpers/session_helper.rb
module SessionHelper
end

08-rails/tunr/app/helpers/users_helper.rb
module UsersHelper
end

08-rails/tunr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tunr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav>
        <% if @current_user.present? %>
          <%= link_to "Users", users_path if @current_user.admin? %>
          <%= link_to "New mixtape", new_mixtape_path %>
          <%= link_to "Logout #{ @current_user.email }", login_path, :method => 'delete' %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Sign in", login_path %>
        <% end %>
      </nav>

      <%= yield %>
    </div>

  </body>
</html>