08-rails/solar-system/config/routes.rb
Rails.application.routes.draw do
  root :to => 'planets#index'
  get '/planets' => 'planets#index'
  get '/planets/new' => 'planets#new', :as => :new_planet # pedantic
  post '/planets' => 'planets#create'
  get '/planets/:id' => 'planets#show', :as => :planet
  get '/planets/:id/edit' => 'planets#edit', :as => :edit_planet
  post '/planets/:id' => 'planets#update'
  delete '/planets/:id' => 'planets#destroy'
end

08-rails/solar-system/app/models/planet.rb
class Planet < ActiveRecord::Base
end

08-rails/solar-system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token # You only need this for handwritten POST forms.
end

08-rails/solar-system/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find params[:id]
  end

  def new
  end

  def create
    planet = Planet.create :name => params[:name], :image => params[:image], :orbit => params[:orbit], :diameter => params[:diameter], :mass => params[:mass], :moons => params[:moons]
    redirect_to planet_path(planet.id) # show page
  end

  def edit
    @planet = Planet.find params[:id]
  end

  def update
    planet = Planet.find params[:id]
    planet.name = params[:name]
    planet.image = params[:image]
    planet.orbit = params[:orbit]
    planet.diameter = params[:diameter]
    planet.mass = params[:mass]
    planet.moons = params[:moons]
    planet.save
    redirect_to planet_path(planet.id) # GET show
  end

  def destroy
    planet = Planet.find params[:id]
    planet.destroy
    redirect_to planets_path
  end
end

08-rails/solar-system/app/views/planets/edit.html.erb
<h2>Edit Planet</h2>

<form action="<%= planet_path(@planet.id) %>" method="post">
  <label>
    Name:
    <input name="name" required value="<%= @planet.name %>">
  </label>

  <label>
    Image:
    <input type="url" name="image" value="<%= @planet.image %>">
  </label>

  <label>
    Orbit:
    <input type="number" name="orbit" value="<%= @planet.orbit %>">
  </label>

  <label>
    Diameter:
    <input type="number" name="diameter" value="<%= @planet.diameter %>">
  </label>

  <label>
    Mass:
    <input type="number" name="mass" value="<%= @planet.mass %>">
  </label>

  <label>
    Moons:
    <input type="number" name="moons" value="<%= @planet.moons %>">
  </label>

  <button>Update planet</button>
</form>

08-rails/solar-system/app/views/planets/index.html.erb
<h1>All Planets</h1>

<% @planets.each do |planet| %>
  <p><%= link_to planet.name, planet_path(planet.id) %> has <%= pluralize planet.moons, 'moon' %>.</p>
<% end %>

08-rails/solar-system/app/views/planets/new.html.erb
<h2>New Planet</h2>

<form action="<%= planets_path %>" method="post">
  <label>
    Name:
    <input name="name" required>
  </label>

  <label>
    Image:
    <input type="url" name="image">
  </label>

  <label>
    Orbit:
    <input type="number" name="orbit">
  </label>

  <label>
    Diameter:
    <input type="number" name="diameter">
  </label>

  <label>
    Mass:
    <input type="number" name="mass">
  </label>

  <label>
    Moons:
    <input type="number" name="moons">
  </label>

  <button>Create planet</button>
</form>

08-rails/solar-system/app/views/planets/show.html.erb
<h2><%= @planet.name %></h2>

<%= image_tag @planet.image, :class => 'feature' if @planet.image.present? %>

<ul>
  <li>Name: <%= @planet.name %></li>
  <li>Orbit: <%= @planet.orbit %></li>
  <li>Diameter: <%= @planet.diameter %></li>
  <li>Mass: <%= @planet.mass %></li>
  <li>Moons: <%= @planet.moons %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit planet', edit_planet_path(@planet.id) %>
  <%= button_to 'Delete planet',  planet_path(@planet.id), :method => 'delete' %>
</div>